### ISSUE TITLE
exec should enforce a timeout

### ISSUE THREAD

**Issue by dsnet** [appnaconda/tplink#3]
The logic of [`exec`](https://github.com/appnaconda/tplink/blob/eddaff1c9c5da8828cdeaab8a82ab50f5921f989/tplink.go#L358-L377) does not enforce any network timeouts. This is problematic because the logic blocks on reading a packet from the the remote device. However, UDP is not a reliable transport, so there is no guarantee that the response ever arrives. In such a situation, `exec` gets stuck forever waiting for a packet that will never arrive.

**Comment by appnaconda** [comment]
@dsnet sorry for my late response, i've been a little bit busy lately. Good catch, i'm gonna fix this and will add support for more devices such as the `LB100` light bulb, etc soon.
